package:
  name: gasp
  version: 1.0.0

source:
  git_rev: v1.0.0
  git_url: https://github.com/abailoni/GASP.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python 3.7
    - nifty
    - vigra

#test:
#  requires:
#    - pytest
#  run:
#    - pytest tests/

about:
  home: https://github.com/abailoni/GASP
